In [2]:
#Dependencies and Setup
import pandas as pd
import numpy as np

In [3]:
#File to Load
file_to_load = "purchase_data.csv"

In [4]:
#Read Purchasing File and store into Pandas data frame
df_purchase_data = pd.read_csv(file_to_load, delimiter = ",", encoding="utf-8-sig")
df_purchase_data

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44
5,5,Yalae81,22,Male,81,Dreamkiss,3.61
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67
8,8,Undjask33,22,Male,21,Souleater,1.10
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89
16,16,Lisirra25,20,Male,40,Second Chance,2.52
17,17,Zontibe81,21,Male,161,Devine,1.76
18,18,Reunasu60,22,Female,82,Nirvana,4.90
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81
23,23,Eyrian71,40,Male,151,Severance,3.40
24,24,Siala43,30,Male,141,Persuasion,3.19
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
26,26,Lirtossa84,11,Male,71,Demise,1.61
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16
...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,3.15
756,756,Ilast79,20,Male,73,Ritual Mace,2.05
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60
758,758,Iral74,21,Male,182,Toothpick,4.03
759,759,Tyaelorap29,25,Male,72,Winter's Bite,3.77
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,2.38
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70
762,762,Asur53,26,Male,110,Suspension,1.44
763,763,Lassilsala30,21,Male,85,Malificent Bag,1.75
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,4.07
765,765,Irith83,18,Male,130,Alpha,2.07
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14
767,767,Ilmol66,8,Female,92,Final Critic,4.88
768,768,Assassasta79,38,Male,92,Final Critic,4.88
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58
770,770,Lirtosia63,34,Male,12,Dawne,1.02
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,3.58
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02
774,774,Jiskjask80,11,Male,101,Final Critic,4.19
775,775,Aethedru70,21,Female,60,Wolf,3.54
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46
778,778,Sisur91,7,Male,101,Final Critic,4.19
779,779,Ennrian78,24,Male,50,Dawn,4.60

In [5]:
#Player Count: Display the total number of players(part 1)
player_count = df_purchase_data["SN"].nunique()
player_count

576

In [6]:
#Player Count: Display the total number of players(part 2)
dictionary = {'Total Players' : 576}
player_count_series = pd.Series(dictionary)
player_count_series

Total Players    576
dtype: int64

In [7]:
#Purchasing Analysis (Total): Run basic calculations to obtain number of unique items, average price, etc.
#unique items
unique_item_count = df_purchase_data["Item ID"].nunique()
print(f"Number of Unique Items: {unique_item_count}")

#average price
average_price = df_purchase_data["Price"].mean()
average_price = round(average_price, 2)
print(f"Average Price: ${average_price}")

#Number of purchases
number_of_purchases = df_purchase_data["Purchase ID"].nunique()
print(f"Number of Purchases: {number_of_purchases}")

#Total revenue
total_revenue = df_purchase_data["Price"].sum()
total_revenue = '{:,}'.format(total_revenue)
print(f"Total Revenue: ${total_revenue}\n")

Number of Unique Items: 183
Average Price: $3.05
Number of Purchases: 780
Total Revenue: $2,379.77

In [8]:
#Player Analysis (Total): Create and display a summary data frame to hold the results
df_purchase_data.dicts = pd.DataFrame(
                          {"Number of Unique Items": ["183"],
                           "Average Price": ["$3.05"],
                           "Number of Purchases": ["780"],
                           "Total Revenue": ["$2,379.77"]
                          })
#df_purchase_data.dicts = [{"Number of Unique Items": "183"},
#                         {"Average Price": "$3.05"},
#                         {"Number of Purchases": "780"},
#                         {"Total Revenue": "$2,379.77"}]
#df_purchase_data.dicts = [{"Total Players": [player_count]},
#                         {"Unique Item Count": [unique_item_count]},
#                         {"Average Price": [average_price]},
#                         {"Number of Purchases": [number_of_purchases]},
#                         {"Total Revenue": [total_revenue]}]
df_purchase_data = pd.DataFrame(df_purchase_data.dicts)
df_purchase_data

C:\Users\17324\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access

  Number of Unique Items Average Price Number of Purchases Total Revenue
0                    183         $3.05                 780     $2,379.77

In [9]:
#Read Purchasing File and store into Pandas data frame
df_purchase_data = pd.read_csv(file_to_load, delimiter = ",", encoding="utf-8-sig")
df_purchase_data

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44
5,5,Yalae81,22,Male,81,Dreamkiss,3.61
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67
8,8,Undjask33,22,Male,21,Souleater,1.10
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89
16,16,Lisirra25,20,Male,40,Second Chance,2.52
17,17,Zontibe81,21,Male,161,Devine,1.76
18,18,Reunasu60,22,Female,82,Nirvana,4.90
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81
23,23,Eyrian71,40,Male,151,Severance,3.40
24,24,Siala43,30,Male,141,Persuasion,3.19
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
26,26,Lirtossa84,11,Male,71,Demise,1.61
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16
...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,3.15
756,756,Ilast79,20,Male,73,Ritual Mace,2.05
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60
758,758,Iral74,21,Male,182,Toothpick,4.03
759,759,Tyaelorap29,25,Male,72,Winter's Bite,3.77
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,2.38
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70
762,762,Asur53,26,Male,110,Suspension,1.44
763,763,Lassilsala30,21,Male,85,Malificent Bag,1.75
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,4.07
765,765,Irith83,18,Male,130,Alpha,2.07
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14
767,767,Ilmol66,8,Female,92,Final Critic,4.88
768,768,Assassasta79,38,Male,92,Final Critic,4.88
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58
770,770,Lirtosia63,34,Male,12,Dawne,1.02
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,3.58
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02
774,774,Jiskjask80,11,Male,101,Final Critic,4.19
775,775,Aethedru70,21,Female,60,Wolf,3.54
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46
778,778,Sisur91,7,Male,101,Final Critic,4.19
779,779,Ennrian78,24,Male,50,Dawn,4.60

In [10]:
#Gender Demographics (Total Count)
purch_users_df = df_purchase_data[["Gender", "SN"]].drop_duplicates()
purch_users_df
purch_group = purch_users_df.groupby(["Gender"])
purch_group
summ_totalcount_df = purch_group.count()
summ_totalcount_df.rename(columns={'SN':'Total Count'}, inplace=True)
summ_totalcount_df = summ_totalcount_df.sort_values(["Total Count"], ascending=False)
summ_totalcount_df
summ_totalcount_df['Total Count']

Gender
Male                     484
Female                    81
Other / Non-Disclosed     11
Name: Total Count, dtype: int64

In [11]:
#Gender Demographics (Percentage of Players)
purch_users_df = df_purchase_data[["Gender", "SN"]].drop_duplicates()
purch_group = purch_users_df.groupby(["Gender"])
summ_demo_df = purch_group.count()
summ_demo_df
unique_player_count = df_purchase_data["SN"].nunique()
purch_percent_df = ((summ_demo_df/unique_player_count) * 100).round(2).astype(str) + '%'
purch_percent_df = round(purch_percent_df, 2)
purch_percent_df.rename(columns={'SN':'Percentage of Players'}, inplace=True)
purch_percent_df = purch_percent_df.sort_values(["Percentage of Players"], ascending=False)
purch_percent_df
#purch_users_df
print(purch_percent_df)

                      Percentage of Players
Gender
Male                                 84.03%
Female                               14.06%
Other / Non-Disclosed                 1.91%

In [12]:
#Gender Demographics (Merge Total Count and Percentage of Players into one dataframe)
merge_table = pd.merge(summ_demo_df, purch_percent_df, on="Gender")
merge_table.rename(columns={'SN':'Total Count'}, inplace=True)
merge_table = merge_table.sort_values(["Total Count"], ascending=False)
merge_table

                       Total Count Percentage of Players
Gender
Male                           484                84.03%
Female                          81                14.06%
Other / Non-Disclosed           11                 1.91%

In [13]:
#Purchasing Analysis (Gender)
#Run basic calculations to obtain purchase count, avg purchase price, total purchase value, avg total per person by gender

In [14]:
#Purchasing Analysis (Gender)
#Calculate purchase count by gender
purch_count_df = df_purchase_data[["Gender", "Purchase ID"]].drop_duplicates()
purch_group = purch_count_df.groupby(["Gender"])
summ_purchcount_df = purch_group.count()
summ_purchcount_df.rename(columns={'Purchase ID':'Purchase Count'}, inplace=True)
summ_purchcount_df

                       Purchase Count
Gender
Female                            113
Male                              652
Other / Non-Disclosed              15

In [15]:
#Purchasing Analysis (Gender)
#Calculate average purchase price by gender
avg_price_df = df_purchase_data[["Gender", "Price"]]
purch_group = avg_price_df.groupby(["Gender"])
summ_avgprice_df = purch_group.mean()
summ_avgprice_df = round(summ_avgprice_df, 2)
summ_avgprice_df.rename(columns={'Price' : 'Average Purchase Price'}, inplace=True)
pd.options.display.float_format = '${:,.2f}'.format
summ_avgprice_df
#print(f"Average Purchase Price: ${summ_avgprice_df}\n")

                       Average Purchase Price
Gender
Female                                  $3.20
Male                                    $3.02
Other / Non-Disclosed                   $3.35

In [16]:
#Purchasing Analysis (Gender)
#Calculate total purchase value by gender
tot_purchvalue_df = df_purchase_data[["Gender", "Price"]]
purch_group = tot_purchvalue_df.groupby(["Gender"])
summ_purchvalue_df = purch_group.sum()
summ_purchvalue_df.rename(columns={'Price' : 'Total Purchase Value'}, inplace=True)
summ_purchvalue_df

                       Total Purchase Value
Gender
Female                              $361.94
Male                              $1,967.64
Other / Non-Disclosed                $50.19

In [17]:
#Purchasing Analysis (Gender)
#Calculate average total purchase per person by gender

avgtot_purchperperson_df = df_purchase_data[["Gender", "Price"]]
purchperperson_group = avgtot_purchperperson_df.groupby(["Gender"])
total_purchases_df = purchperperson_group.sum()

total_purchases_df['Gender Count'] = summ_totalcount_df['Total Count']
#1 Create 3 Variables connecting the total purchase df Price & gender count
female_avg_prc = total_purchases_df['Price'][0]/total_purchases_df['Gender Count'][0]
male_avg_prc = total_purchases_df['Price'][1]/total_purchases_df['Gender Count'][1]
other_avg_prc = total_purchases_df['Price'][2]/total_purchases_df['Gender Count'][2]
#2 Create a list or Panda Series with 3 Variable

avg_prc_series = pd.Series([female_avg_prc,male_avg_prc,other_avg_prc])
#3 Create a DataFrame Column summ_purchperperson_df["Avg Total Purchase per Person"] and put list/Series into column

Brand_New_DF = pd.DataFrame()
Brand_New_DF['Avg Total Purchase Per Person'] = round(avg_prc_series, 2)
Brand_New_DF.rename(index={0: 'Female'}, inplace=True)
Brand_New_DF.rename(index={1: 'Male'}, inplace=True)
Brand_New_DF.rename(index={2: 'Other / Non-Disclosed'}, inplace=True)
Brand_New_DF.index.name='Gender'
Brand_New_DF

                       Avg Total Purchase Per Person
Gender
Female                                         $4.47
Male                                           $4.07
Other / Non-Disclosed                          $4.56

In [18]:
df_col = pd.concat([summ_purchcount_df, summ_avgprice_df, summ_purchvalue_df, Brand_New_DF], axis=1)
df_col

,Purchase Count,Average Purchase Price,Total Purchase Value,Avg Total Purchase Per Person
Gender,,,,
Female,113,$3.20,$361.94,$4.47
Male,652,$3.02,"$1,967.64",$4.07
Other / Non-Disclosed,15,$3.35,$50.19,$4.56

In [19]:
#Age Demographics
#Figure out the minimum and maximum ages for players
print(f'Max age: {df_purchase_data["Age"].max()}')
print(f'Min age: {df_purchase_data["Age"].min()}')
max_age = df_purchase_data["Age"].max()
min_age = df_purchase_data["Age"].max()

Max age: 45
Min age: 7

In [20]:
#Age Demographics: Categorize existing players using age bins.
#Create bins for ages
bins = [6, 9, 14, 19, 24, 29, 34, 39, 45]
#df_purchase_data["Age"]
group_names = ["<10", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40+"]

In [21]:
df_purchase_data["Age Range"] = pd.cut(df_purchase_data["Age"], bins, labels=group_names)
df_purchase_data

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Age Range
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",$3.53,20-24
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,$1.56,40+
2,2,Ithergue48,24,Male,92,Final Critic,$4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,$3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,$1.44,20-24
5,5,Yalae81,22,Male,81,Dreamkiss,$3.61,20-24
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",$2.18,35-39
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,$2.67,20-24
8,8,Undjask33,22,Male,21,Souleater,$1.10,20-24
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,$3.58,35-39
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,$4.74,20-24
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,$2.67,20-24
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,$4.18,20-24
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,$1.70,20-24
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,$4.86,35-39
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",$2.89,20-24
16,16,Lisirra25,20,Male,40,Second Chance,$2.52,20-24
17,17,Zontibe81,21,Male,161,Devine,$1.76,20-24
18,18,Reunasu60,22,Female,82,Nirvana,$4.90,20-24
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",$4.64,30-34
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",$4.60,20-24
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",$1.48,20-24
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,$3.81,35-39
23,23,Eyrian71,40,Male,151,Severance,$3.40,40+
24,24,Siala43,30,Male,141,Persuasion,$3.19,30-34
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",$4.23,25-29
26,26,Lirtossa84,11,Male,71,Demise,$1.61,10-14
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,$3.09,<10
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",$4.32,20-24
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",$3.16,20-24
...,...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",$3.61,20-24
751,751,Lisjaskan36,11,Male,180,Stormcaller,$3.36,10-14
752,752,Mindjasksya61,17,Male,112,Worldbreaker,$2.60,15-19
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",$4.23,35-39
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",$4.05,20-24
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,$3.15,10-14
756,756,Ilast79,20,Male,73,Ritual Mace,$2.05,20-24
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",$4.60,15-19
758,758,Iral74,21,Male,182,Toothpick,$4.03,20-24
759,759,Tyaelorap29,25,Male,72,Winter's Bite,$3.77,25-29
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,$2.38,20-24
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",$1.70,40+
762,762,Asur53,26,Male,110,Suspension,$1.44,25-29
763,763,Lassilsala30,21,Male,85,Malificent Bag,$1.75,20-24
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,$4.07,15-19
765,765,Irith83,18,Male,130,Alpha,$2.07,15-19
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",$4.14,20-24
767,767,Ilmol66,8,Female,92,Final Critic,$4.88,<10
768,768,Assassasta79,38,Male,92,Final Critic,$4.88,35-39
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,$4.58,15-19
770,770,Lirtosia63,34,Male,12,Dawne,$1.02,30-34
771,771,Iskossasda43,16,Male,25,Hero Cane,$4.35,15-19
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,$3.58,25-29
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",$1.02,20-24
774,774,Jiskjask80,11,Male,101,Final Critic,$4.19,10-14
775,775,Aethedru70,21,Female,60,Wolf,$3.54,20-24
776,776,Iral74,21,Male,164,Exiled Doomblade,$1.63,20-24
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",$3.46,20-24
778,778,Sisur91,7,Male,101,Final Critic,$4.19,<10
779,779,Ennrian78,24,Male,50,Dawn,$4.60,20-24

In [22]:
#Age Demographics (Total Count)
age_range_df = df_purchase_data[["Age Range", "SN"]].drop_duplicates()
age_range_df
age_group = age_range_df.groupby(["Age Range"])
age_group
summ_age_df = age_group.count()
summ_age_df.rename(columns={"SN":"Total Count"}, inplace=True)
summ_age_df = summ_age_df.sort_values(["Age Range"], ascending=True)
summ_age_df
print(summ_age_df)

           Total Count
Age Range
<10                 17
10-14               22
15-19              107
20-24              258
25-29               77
30-34               52
35-39               31
40+                 12

In [23]:
#Age Demographics (Percentage of Players)
age_range_percent_df = df_purchase_data[["Age Range", "SN"]].drop_duplicates()
age_group = age_range_percent_df.groupby(["Age Range"])
summ_age_df = age_group.count()
summ_age_df
unique_player_count = df_purchase_data["SN"].nunique()
purch_percent_df = ((summ_age_df/unique_player_count) * 100).round(2).astype(str) + '%'
purch_percent_df.rename(columns={'SN':'Percentage of Players'}, inplace=True)
purch_percent_df = purch_percent_df.sort_values(["Age Range"], ascending=True)
purch_percent_df = purch_percent_df.replace('$', '')
purch_percent_df
print(purch_percent_df)

          Percentage of Players
Age Range
<10                       2.95%
10-14                     3.82%
15-19                    18.58%
20-24                    44.79%
25-29                    13.37%
30-34                     9.03%
35-39                     5.38%
40+                       2.08%

In [24]:
#Age Demographics (Merge Total Count and Percentage of Players into one dataframe)
merge_table = pd.merge(summ_age_df, purch_percent_df, on="Age Range")
merge_table.rename(columns={'SN':'Total Count'}, inplace=True)
merge_table = merge_table.sort_values(["Age Range"], ascending=True)
merge_table

           Total Count Percentage of Players
Age Range
<10                 17                 2.95%
10-14               22                 3.82%
15-19              107                18.58%
20-24              258                44.79%
25-29               77                13.37%
30-34               52                 9.03%
35-39               31                 5.38%
40+                 12                 2.08%

In [25]:
#Purchasing Analysis (Age)
#Bin the purchase_data data frame by age
#Figure out the minimum and maximum ages for players
print(f'Max age: {df_purchase_data["Age"].max()}')
print(f'Min age: {df_purchase_data["Age"].min()}')
max_age = df_purchase_data["Age"].max()
min_age = df_purchase_data["Age"].max()

Max age: 45
Min age: 7

In [26]:
#Purchasing Analysis (Age)
#Bin the purchase_data data frame by age
bins = [6, 9, 14, 19, 24, 29, 34, 39, 45]
#df_purchase_data["Age"]
group_names = ["<10", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40+"]

In [27]:
df_purchase_data["Age Range"] = pd.cut(df_purchase_data["Age"], bins, labels=group_names)
df_purchase_data

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Age Range
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",$3.53,20-24
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,$1.56,40+
2,2,Ithergue48,24,Male,92,Final Critic,$4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,$3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,$1.44,20-24
5,5,Yalae81,22,Male,81,Dreamkiss,$3.61,20-24
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",$2.18,35-39
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,$2.67,20-24
8,8,Undjask33,22,Male,21,Souleater,$1.10,20-24
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,$3.58,35-39
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,$4.74,20-24
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,$2.67,20-24
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,$4.18,20-24
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,$1.70,20-24
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,$4.86,35-39
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",$2.89,20-24
16,16,Lisirra25,20,Male,40,Second Chance,$2.52,20-24
17,17,Zontibe81,21,Male,161,Devine,$1.76,20-24
18,18,Reunasu60,22,Female,82,Nirvana,$4.90,20-24
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",$4.64,30-34
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",$4.60,20-24
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",$1.48,20-24
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,$3.81,35-39
23,23,Eyrian71,40,Male,151,Severance,$3.40,40+
24,24,Siala43,30,Male,141,Persuasion,$3.19,30-34
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",$4.23,25-29
26,26,Lirtossa84,11,Male,71,Demise,$1.61,10-14
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,$3.09,<10
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",$4.32,20-24
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",$3.16,20-24
...,...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",$3.61,20-24
751,751,Lisjaskan36,11,Male,180,Stormcaller,$3.36,10-14
752,752,Mindjasksya61,17,Male,112,Worldbreaker,$2.60,15-19
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",$4.23,35-39
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",$4.05,20-24
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,$3.15,10-14
756,756,Ilast79,20,Male,73,Ritual Mace,$2.05,20-24
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",$4.60,15-19
758,758,Iral74,21,Male,182,Toothpick,$4.03,20-24
759,759,Tyaelorap29,25,Male,72,Winter's Bite,$3.77,25-29
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,$2.38,20-24
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",$1.70,40+
762,762,Asur53,26,Male,110,Suspension,$1.44,25-29
763,763,Lassilsala30,21,Male,85,Malificent Bag,$1.75,20-24
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,$4.07,15-19
765,765,Irith83,18,Male,130,Alpha,$2.07,15-19
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",$4.14,20-24
767,767,Ilmol66,8,Female,92,Final Critic,$4.88,<10
768,768,Assassasta79,38,Male,92,Final Critic,$4.88,35-39
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,$4.58,15-19
770,770,Lirtosia63,34,Male,12,Dawne,$1.02,30-34
771,771,Iskossasda43,16,Male,25,Hero Cane,$4.35,15-19
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,$3.58,25-29
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",$1.02,20-24
774,774,Jiskjask80,11,Male,101,Final Critic,$4.19,10-14
775,775,Aethedru70,21,Female,60,Wolf,$3.54,20-24
776,776,Iral74,21,Male,164,Exiled Doomblade,$1.63,20-24
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",$3.46,20-24
778,778,Sisur91,7,Male,101,Final Critic,$4.19,<10
779,779,Ennrian78,24,Male,50,Dawn,$4.60,20-24

In [28]:
#Calculate purchase count by age
purch_count_age_df = df_purchase_data[["Age Range", "Purchase ID"]].drop_duplicates()
purch_group_age = purch_count_age_df.groupby(["Age Range"])
summ_purchcountage_df = purch_group_age.count()
summ_purchcountage_df.rename(columns={'Purchase ID':'Purchase Count'}, inplace=True)
summ_purchcountage_df

           Purchase Count
Age Range
<10                    23
10-14                  28
15-19                 136
20-24                 365
25-29                 101
30-34                  73
35-39                  41
40+                    13

In [29]:
#Calculate average purchase price by age
avg_priceage_df = df_purchase_data[["Age Range", "Price"]]
purch_groupprice_age = avg_priceage_df.groupby(["Age Range"])
summ_avgpriceage_df = purch_groupprice_age.mean()
summ_avgpriceage_df = round(summ_avgpriceage_df, 2)
summ_avgpriceage_df.rename(columns={'Price' : 'Average Purchase Price'}, inplace=True)
pd.options.display.float_format = '${:,.2f}'.format
summ_avgpriceage_df

           Average Purchase Price
Age Range
<10                         $3.35
10-14                       $2.96
15-19                       $3.04
20-24                       $3.05
25-29                       $2.90
30-34                       $2.93
35-39                       $3.60
40+                         $2.94

In [30]:
#Calculate total purchase value by age
tot_purchvalueage_df = df_purchase_data[["Age Range", "Price"]]
purch_groupvalueage = tot_purchvalueage_df.groupby(["Age Range"])
summ_purchvalueage_df = purch_groupvalueage.sum()
summ_purchvalueage_df.rename(columns={'Price' : 'Total Purchase Value'}, inplace=True)
summ_purchvalueage_df

           Total Purchase Value
Age Range
<10                      $77.13
10-14                    $82.78
15-19                   $412.89
20-24                 $1,114.06
25-29                   $293.00
30-34                   $214.00
35-39                   $147.67
40+                      $38.24

In [31]:
#Calculate average total purchase per person
avgtot_purchperpersonage_df = df_purchase_data[["Age Range", "Price"]]
purchperpersonage_group = avgtot_purchperpersonage_df.groupby(["Age Range"])
total_purchasesage_df = purchperpersonage_group.sum()

total_purchasesage_df['Age Range'] = summ_age_df

#1 Create 8 Variables connecting the total purchasesage df Price & Age range
underten_avg_prc = total_purchasesage_df['Price'][0]/total_purchasesage_df['Age Range'][0]
tentofourteen_avg_prc = total_purchasesage_df['Price'][1]/total_purchasesage_df['Age Range'][1]
fifteentonineteen_avg_prc = total_purchasesage_df['Price'][2]/total_purchasesage_df['Age Range'][2]
twentytotwentyfour_avg_prc = total_purchasesage_df['Price'][3]/total_purchasesage_df['Age Range'][3]
twentyfivetotwentynine_avg_prc = total_purchasesage_df['Price'][4]/total_purchasesage_df['Age Range'][4]
thirtytothirtyfour_avg_prc = total_purchasesage_df['Price'][5]/total_purchasesage_df['Age Range'][5]
thirtyfivetothirtynine_avg_prc = total_purchasesage_df['Price'][6]/total_purchasesage_df['Age Range'][6]
fortyandabove_avg_prc = total_purchasesage_df['Price'][7]/total_purchasesage_df['Age Range'][7]

#2 Create a list or Panda Series with 8 Variables
avg_prcage_series = pd.Series([underten_avg_prc,tentofourteen_avg_prc,fifteentonineteen_avg_prc,twentytotwentyfour_avg_prc,twentyfivetotwentynine_avg_prc,thirtytothirtyfour_avg_prc,thirtyfivetothirtynine_avg_prc,fortyandabove_avg_prc])

#3 Create a DataFrame Column summ_purchperperson_df["Avg Total Purchase per Person"] and put list/Series into column
Brand_New2_DF = pd.DataFrame()
Brand_New2_DF['Avg Total Purchase Per Person'] = round(avg_prcage_series, 2)
Brand_New2_DF.rename(index={0: '<10'}, inplace=True)
Brand_New2_DF.rename(index={1: '10-14'}, inplace=True)
Brand_New2_DF.rename(index={2: '15-19'}, inplace=True)
Brand_New2_DF.rename(index={3: '20-24'}, inplace=True)
Brand_New2_DF.rename(index={4: '25-29'}, inplace=True)
Brand_New2_DF.rename(index={5: '30-34'}, inplace=True)
Brand_New2_DF.rename(index={6: '35-39'}, inplace=True)
Brand_New2_DF.rename(index={7: '40+'}, inplace=True)
Brand_New2_DF.index.name='Age Range'
Brand_New2_DF

           Avg Total Purchase Per Person
Age Range
<10                                $4.54
10-14                              $3.76
15-19                              $3.86
20-24                              $4.32
25-29                              $3.81
30-34                              $4.12
35-39                              $4.76
40+                                $3.19

In [32]:
df_col = pd.concat([summ_purchcountage_df, summ_avgpriceage_df, summ_purchvalueage_df, Brand_New2_DF], axis=1)
df_col

,Purchase Count,Average Purchase Price,Total Purchase Value,Avg Total Purchase Per Person
Age Range,,,,
<10,23,$3.35,$77.13,$4.54
10-14,28,$2.96,$82.78,$3.76
15-19,136,$3.04,$412.89,$3.86
20-24,365,$3.05,"$1,114.06",$4.32
25-29,101,$2.90,$293.00,$3.81
30-34,73,$2.93,$214.00,$4.12
35-39,41,$3.60,$147.67,$4.76
40+,13,$2.94,$38.24,$3.19

In [33]:
#Read Purchasing File and store into Pandas data frame
df_purchase_data = pd.read_csv(file_to_load, delimiter = ",", encoding="utf-8-sig")
df_purchase_data

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",$3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,$1.56
2,2,Ithergue48,24,Male,92,Final Critic,$4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,$3.27
4,4,Iskosia90,23,Male,131,Fury,$1.44
5,5,Yalae81,22,Male,81,Dreamkiss,$3.61
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",$2.18
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,$2.67
8,8,Undjask33,22,Male,21,Souleater,$1.10
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,$3.58
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,$4.74
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,$2.67
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,$4.18
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,$1.70
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,$4.86
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",$2.89
16,16,Lisirra25,20,Male,40,Second Chance,$2.52
17,17,Zontibe81,21,Male,161,Devine,$1.76
18,18,Reunasu60,22,Female,82,Nirvana,$4.90
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",$4.64
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",$4.60
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",$1.48
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,$3.81
23,23,Eyrian71,40,Male,151,Severance,$3.40
24,24,Siala43,30,Male,141,Persuasion,$3.19
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",$4.23
26,26,Lirtossa84,11,Male,71,Demise,$1.61
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,$3.09
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",$4.32
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",$3.16
...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",$3.61
751,751,Lisjaskan36,11,Male,180,Stormcaller,$3.36
752,752,Mindjasksya61,17,Male,112,Worldbreaker,$2.60
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",$4.23
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",$4.05
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,$3.15
756,756,Ilast79,20,Male,73,Ritual Mace,$2.05
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",$4.60
758,758,Iral74,21,Male,182,Toothpick,$4.03
759,759,Tyaelorap29,25,Male,72,Winter's Bite,$3.77
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,$2.38
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",$1.70
762,762,Asur53,26,Male,110,Suspension,$1.44
763,763,Lassilsala30,21,Male,85,Malificent Bag,$1.75
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,$4.07
765,765,Irith83,18,Male,130,Alpha,$2.07
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",$4.14
767,767,Ilmol66,8,Female,92,Final Critic,$4.88
768,768,Assassasta79,38,Male,92,Final Critic,$4.88
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,$4.58
770,770,Lirtosia63,34,Male,12,Dawne,$1.02
771,771,Iskossasda43,16,Male,25,Hero Cane,$4.35
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,$3.58
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",$1.02
774,774,Jiskjask80,11,Male,101,Final Critic,$4.19
775,775,Aethedru70,21,Female,60,Wolf,$3.54
776,776,Iral74,21,Male,164,Exiled Doomblade,$1.63
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",$3.46
778,778,Sisur91,7,Male,101,Final Critic,$4.19
779,779,Ennrian78,24,Male,50,Dawn,$4.60

In [34]:
#Top Spenders
#Identify the top 5 spenders in teh game by total purchase value, then list (in a table): SN, Purchase Count,
#Average Purchase Price, Total Purchase Value
#Purchase Count
purch_count_top_df = df_purchase_data[["SN", "Purchase ID"]].drop_duplicates()
purch_group_top = purch_count_top_df.groupby(["SN"])
summ_purchcounttop_df = purch_group_top.count()
summ_purchcounttop_df.rename(columns={'Purchase ID':'Purchase Count'}, inplace=True)
summ_purchcounttop_df = summ_purchcounttop_df.sort_values(["Purchase Count"], ascending=False)
summ_purchcounttop_df.index.name='Player Name'
summ_purchcounttop_df.head(10)

             Purchase Count
Player Name
Lisosia93                 5
Iral74                    4
Idastidru52               4
Asur53                    3
Inguron55                 3
Aina42                    3
Ilarin91                  3
Idai61                    3
Umolrian85                3
Ialallo29                 3

In [35]:
#Top Spenders
#Identify the top 5 spenders in teh game by total purchase value, then list (in a table): SN, Purchase Count,
#Average Purchase Price, Total Purchase Value
#Average Purchase Price
avg_pricetop_df = df_purchase_data[["SN", "Price"]]
purch_groupprice_top = avg_pricetop_df.groupby(["SN"])
summ_avgpricetop_df = purch_groupprice_top.mean()
summ_avgpricetop_df = round(summ_avgpricetop_df, 2)
summ_avgpricetop_df = summ_avgpricetop_df.sort_values(["Price"], ascending=False)
summ_avgpricetop_df.rename(columns={'Price' : 'Average Purchase Price'}, inplace=True)
summ_avgpricetop_df = summ_avgpricetop_df.replace('\$','', regex=True).astype(float)
summ_avgpricetop_df.index.name='Player Name'
summ_avgpricetop_df.head(10)

                Average Purchase Price
Player Name
Dyally87                         $4.99
Yarithsurgue62                   $4.94
Chanirrasta87                    $4.94
Lirtilsa71                       $4.94
Ririp86                          $4.94
Mindossa76                       $4.93
Chadjask77                       $4.93
Aeda94                           $4.91
Filurarn35                       $4.91
Aerithnuphos61                   $4.91

In [36]:
#Top Spenders
#Identify the top 5 spenders in teh game by total purchase value, then list (in a table): SN, Purchase Count,
#Average Purchase Price, Total Purchase Value
#Total Purchase Value
summ_purchvaluetop_df = df_purchase_data.groupby(['SN']).agg({'Price':'sum'})
summ_purchvaluetop_df = summ_purchvaluetop_df.sort_values(["Price"], ascending=False)
summ_purchvaluetop_df.rename(columns={'Price' : 'Total Purchase Value'}, inplace=True)
summ_purchvaluetop_df.sort_values(by=["Total Purchase Value"],ascending=False)
summ_purchvaluetop_df.index.name='Player Name'
summ_purchvaluetop_df.head(10)

              Total Purchase Value
Player Name
Lisosia93                   $18.96
Idastidru52                 $15.45
Chamjask73                  $13.83
Iral74                      $13.62
Iskadarya95                 $13.10
Ilarin91                    $12.70
Ialallo29                   $11.84
Tyidaim51                   $11.83
Lassilsala30                $11.51
Chadolyla44                 $11.46

In [37]:
#Top Spenders dataframe by Total Purchase Value
topspenders_df_col = pd.concat([summ_purchcounttop_df, summ_avgpricetop_df, summ_purchvaluetop_df], axis=1)
topspenders_df_col = topspenders_df_col.sort_values(["Total Purchase Value"], ascending=False)
topspenders_df_col.head(5)
#print(topspenders_df_col.head(5))

C:\Users\17324\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

             Purchase Count  Average Purchase Price  Total Purchase Value
Lisosia93                 5                   $3.79                $18.96
Idastidru52               4                   $3.86                $15.45
Chamjask73                3                   $4.61                $13.83
Iral74                    4                   $3.40                $13.62
Iskadarya95               3                   $4.37                $13.10

In [38]:
#Most popular items - purchase count
purch_count_pop_df = df_purchase_data[["Item ID", "Item Name", "Purchase ID"]].drop_duplicates()
purch_group_pop = purch_count_pop_df.groupby(['Item ID', 'Item Name'])
summ_purchcountpop_df = purch_group_pop.count()
summ_purchcountpop_df.rename(columns={'Purchase ID':'Purchase Count'}, inplace=True)
summ_purchcountpop_df.rename(columns={'Price':'Item Price'}, inplace=True)
summ_purchcountpop_df = summ_purchcountpop_df.sort_values(["Purchase Count"], ascending=False)
summ_purchcountpop_df.head(10)

                                                      Purchase Count
Item ID Item Name
178     Oathbreaker, Last Hope of the Breaking Storm              12
145     Fiery Glass Crusader                                       9
108     Extraction, Quickblade Of Trembling Hands                  9
82      Nirvana                                                    9
19      Pursuit, Cudgel of Necromancy                              8
103     Singed Scalpel                                             8
75      Brutality Ivory Warmace                                    8
72      Winter's Bite                                              8
60      Wolf                                                       8
59      Lightning, Etcher of the King                              8

In [39]:
#Most popular items - total purchase value
summ_purchvaluepop_df = df_purchase_data[["Item ID", "Item Name", "Purchase ID", "Price"]]
summ_purchvaluepop_df = df_purchase_data.groupby(['Item ID', 'Item Name']).agg({'Price':'sum'})
summ_purchvaluepop_df = summ_purchvaluepop_df.sort_values(["Price"], ascending=False)
summ_purchcountpop_df.rename(columns={'Purchase ID':'Purchase Count'}, inplace=True)
summ_purchvaluepop_df.rename(columns={'Price' : 'Total Purchase Value'}, inplace=True)
summ_purchvaluepop_df.sort_values(by=["Total Purchase Value"],ascending=False)
summ_purchvaluepop_df.head(10)

                                                      Total Purchase Value
Item ID Item Name
178     Oathbreaker, Last Hope of the Breaking Storm                $50.76
82      Nirvana                                                     $44.10
145     Fiery Glass Crusader                                        $41.22
92      Final Critic                                                $39.04
103     Singed Scalpel                                              $34.80
59      Lightning, Etcher of the King                               $33.84
108     Extraction, Quickblade Of Trembling Hands                   $31.77
78      Glimmer, Ender of the Moon                                  $30.80
72      Winter's Bite                                               $30.16
60      Wolf                                                        $28.32

In [40]:
#Most popular items - Item Price
item_price_df = df_purchase_data[["Item ID", "Item Name", "Price"]]
item_price_df.rename(columns={'Price':'Item Price'}, inplace=True)
item_price_df.head(10)

C:\Users\17324\Anaconda3\lib\site-packages\pandas\core\frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

   Item ID                                  Item Name  Item Price
0      108  Extraction, Quickblade Of Trembling Hands       $3.53
1      143                          Frenzied Scimitar       $1.56
2       92                               Final Critic       $4.88
3      100                                Blindscythe       $3.27
4      131                                       Fury       $1.44
5       81                                  Dreamkiss       $3.61
6      169     Interrogator, Blood Blade of the Queen       $2.18
7      162                              Abyssal Shard       $2.67
8       21                                  Souleater       $1.10
9      136               Ghastly Adamantite Protector       $3.58

In [41]:
#Most popular items - merge purchase count and total purchase value
merge_table = pd.merge(summ_purchcountpop_df, summ_purchvaluepop_df, on=["Item ID", "Item Name"])
merge_table_df = merge_table
purchcountvalue_df = merge_table
purchcountvalue_df.head()

,,Purchase Count,Total Purchase Value
Item ID,Item Name,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,$50.76
145,Fiery Glass Crusader,9,$41.22
108,"Extraction, Quickblade Of Trembling Hands",9,$31.77
82,Nirvana,9,$44.10
19,"Pursuit, Cudgel of Necromancy",8,$8.16

In [50]:
#Most Popular Items by purchase count
mostpop_items_df = pd.merge(purchcountvalue_df, item_price_df, on=["Item ID", "Item Name"]).drop_duplicates()
mostpop_items_df.head(40)

,Item ID,Item Name,Purchase Count,Total Purchase Value,Item Price
0,178,"Oathbreaker, Last Hope of the Breaking Storm",12,$50.76,$4.23
12,145,Fiery Glass Crusader,9,$41.22,$4.58
21,108,"Extraction, Quickblade Of Trembling Hands",9,$31.77,$3.53
30,82,Nirvana,9,$44.10,$4.90
39,19,"Pursuit, Cudgel of Necromancy",8,$8.16,$1.02
47,103,Singed Scalpel,8,$34.80,$4.35
55,75,Brutality Ivory Warmace,8,$19.36,$2.42
63,72,Winter's Bite,8,$30.16,$3.77
71,60,Wolf,8,$28.32,$3.54
79,59,"Lightning, Etcher of the King",8,$33.84,$4.23
87,37,"Shadow Strike, Glory of Ending Hope",8,$25.28,$3.16
95,34,Retribution Axe,8,$17.76,$2.22
103,92,Final Critic,8,$39.04,$4.88
111,53,Vengeance Cleaver,7,$14.35,$2.05
118,110,Suspension,7,$10.08,$1.44
125,7,"Thorn, Satchel of Dark Souls",7,$9.31,$1.33
132,71,Demise,7,$11.27,$1.61
139,117,"Heartstriker, Legacy of the Light",7,$12.53,$1.79
146,159,"Oathbreaker, Spellblade of Trials",7,$21.56,$3.08
153,85,Malificent Bag,7,$12.25,$1.75
160,164,Exiled Doomblade,7,$11.41,$1.63
167,141,Persuasion,7,$22.33,$3.19
174,78,"Glimmer, Ender of the Moon",7,$30.80,$4.40
181,102,Avenger,6,$20.64,$3.44
187,129,"Fate, Vengeance of Eternal Justice",6,$9.24,$1.54
193,93,Apocalyptic Battlescythe,6,$11.82,$1.97
199,54,Eternal Cleaver,6,$15.00,$2.50
205,3,Phantomlight,6,$14.94,$2.49
211,2,Verdict,6,$14.88,$2.48
217,40,Second Chance,6,$15.12,$2.52
223,160,Azurewrath,6,$26.40,$4.40
229,120,Agatha,6,$18.48,$3.08
235,179,"Wolf, Promise of the Moonwalker",6,$26.88,$4.48
241,25,Hero Cane,6,$26.10,$4.35
247,144,Blood Infused Guardian,6,$11.64,$1.94
253,22,Amnesia,6,$13.08,$2.18
259,143,Frenzied Scimitar,6,$9.36,$1.56
265,12,Dawne,6,$6.12,$1.02
271,96,Blood-Forged Skeletal Spine,6,$18.54,$3.09
277,136,Ghastly Adamantite Protector,6,$21.48,$3.58

In [44]:
#Most Profitable Items by total purchase value
mostpop_items_df = pd.merge(purchcountvalue_df, item_price_df, on=["Item ID", "Item Name"]).drop_duplicates()
mostpop_items_df = mostpop_items_df.sort_values(["Total Purchase Value"], ascending=False)
mostpop_items_df.head(5)

,Item ID,Item Name,Purchase Count,Total Purchase Value,Item Price
0,178,"Oathbreaker, Last Hope of the Breaking Storm",12,$50.76,$4.23
30,82,Nirvana,9,$44.10,$4.90
12,145,Fiery Glass Crusader,9,$41.22,$4.58
103,92,Final Critic,8,$39.04,$4.88
47,103,Singed Scalpel,8,$34.80,$4.35

In [462]:
#Three observable trends based on the data
#1.The main market is 15-34 year-olds who account for approximately 85% of the revenue.
#2.Males account for 84% of total purchases and 83% of total revenue
#3.On a micro-age range-level, 20-24 year olds made the most purchases (365 or 47% pf total purchases) and spent the most 
# ($1,114.06 or 47% of total revenue).